name: release-npm

# Run action on every commit to main, release only when requested through commit annotation.
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      manual:
        description: Manually trigger regular release?
        default: regular
        required: true

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with: 
          node-version: 23
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      - run: npm test
      - uses: tobua/release-npm-action@v3
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          MANUAL_TRIGGER: ${{ github.event.inputs.manual }}